# =========================
# Base image
# =========================
FROM php:8.5-apache

# =========================
# Working Dir
# =========================
WORKDIR /var/www

# =========================
# System dependencies
# =========================
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    zip \
    unzip \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libldap2-dev \
    libonig-dev \
    libevent-dev \
    unixodbc-dev \
    ca-certificates \
    curl \
    gnupg \
    wget \
    locales \
 && rm -rf /var/lib/apt/lists/*

# =========================
# PHP extensions (core)
# =========================
RUN docker-php-ext-install mysqli \
 && docker-php-ext-install pdo_mysql \
 && docker-php-ext-install bcmath \
 && docker-php-ext-install mbstring \
 && docker-php-ext-install zip \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install gd \
 && docker-php-ext-install ldap \
 && docker-php-ext-install pcntl \
 && docker-php-ext-install sockets

# =========================
# Apache
# =========================
RUN echo "ServerName localhost" > /etc/apache2/domain.conf \
 && a2enmod rewrite

# =========================
# NodeJS & Composer
# =========================
RUN apt-get update && apt-get install -y nodejs npm \
 && curl -sS https://getcomposer.org/installer | php \
 && mv composer.phar /usr/local/bin/composer \
 && rm -rf /var/lib/apt/lists/*

# =========================
# Copy app
# =========================
COPY . /var/www
RUN chmod -R 777 /var/www

# =========================
# Ports
# =========================
EXPOSE 80 6001 6004

# =========================
# Start Apache
# =========================
CMD ["apache2-foreground"]
